### ISSUE TITLE
Use numeric ICs rather than labels

### ISSUE THREAD

**Issue by cmungall** [IC-FOODS/physical-activity-health-fitness#2]
E.g. $OBO/PAHF+nnnnn

I think Matthew said he did this in Protege?

If not I can help.

**Comment by clairececchini** [comment]
@cmungall I just pushed a new version of the pahf-edit.owl. Is the error still there? If so I'm not sure how to fix it and it would be great if you can help :) thanks!!

**Comment by cmungall** [comment]
yep, it worked!

You can always close or reference tickets in your commit message, e.g. `#2`

The URIs still need tweaked but I will do this as a one-off

**Comment by clairececchini** [comment]
Thanks for checking!
